version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: autentica_db
    restart: always
    environment:
      MYSQL_DATABASE: autentica
      MYSQL_USER: autentica
      MYSQL_PASSWORD: supersecret
      MYSQL_ROOT_PASSWORD: rootsecret
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    container_name: autentica_app
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  dbdata:
